[envs.default]
pre-install-commands = [
  "pip install -r requirements-testing.txt"
]

[envs.default.scripts]
sync = "pip install -r requirements-testing.txt"
test = "pytest --cov-config pyproject.toml {args:test}"
test-windows = """pytest --cov-config pyproject.toml {args:} \
  test/openjd/adaptor_runtime/integ/_named_pipe \
  test/openjd/adaptor_runtime/integ/_utils \
  test/openjd/adaptor_runtime/integ/application_ipc \
  test/openjd/adaptor_runtime/integ/background \
  test/openjd/adaptor_runtime/integ/process \
  test/openjd/adaptor_runtime/unit/adaptors/configuration/test_configuration_manager.py \
  --cov-fail-under=50"""
typing = "mypy {args:src test}"
style = [
  "ruff {args:.}",
  "black --check --diff {args:.}",
]
fmt = [
  "black {args:.}",
  "style",
]
lint = [
  "style",
  "typing",
]

[[envs.all.matrix]]
python = ["3.9", "3.10", "3.11"]

[envs.default.env-vars]
PIP_INDEX_URL="https://aws:{env:CODEARTIFACT_AUTH_TOKEN}@{env:CODEARTIFACT_DOMAIN}-{env:CODEARTIFACT_ACCOUNT_ID}.d.codeartifact.{env:CODEARTIFACT_REGION}.amazonaws.com/pypi/{env:CODEARTIFACT_REPOSITORY}/simple/"

[envs.codebuild.scripts]
build = "hatch build"

[envs.codebuild.env-vars]
PIP_INDEX_URL=""
